version: '2'
services:
  proxy:
    image: quay.io/jmprusi/envoy-wasm:latest
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml
      - ./envoy_wasm_example.wasm:/etc/envoy_wasm_example.wasm
      - ./envoy_filter_http_wasm_example.wasm:/etc/envoy_filter_http_wasm_example.wasm
    command: -c /etc/envoy.yaml
    networks:
      - envoywasm
    expose:
      - "80"
      - "8001"
    ports:
      - "18000:80"
      - "18001:8001"
networks:
  envoywasm: {}

